version: "3.9"

services:
  php-container:
    container_name: php-container
    build:
      context: .
      dockerfile: mysql.dockerfile  
    volumes:
      - ./test:/var/www/html  
    ports:
      - 5000:80  
    depends_on:
      - db-container  

  # Database Container
  db-container:
    image: mysql:latest 
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    restart: always
    environment:
      PMA_HOST: db-container
    depends_on:
      - db-container